# Generated by Django 2.2.4 on 2019-08-13 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='departmentid',
        ),
        migrations.RemoveField(
            model_name='check',
            name='totalsum',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='mealstoorder',
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='api.Department'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServicePercentage'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isitopen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Role'),
        ),
        migrations.DeleteModel(
            name='MealsToOrder',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Meal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='api.Order'),
        ),
    ]
