# Generated by Django 2.2.4 on 2019-08-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190814_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateofadd',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
