# Generated by Django 2.2.4 on 2019-08-16 09:15

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190815_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Order', unique=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(default=None, on_delete=None, to='api.ServicePercentage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isitopen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.Order'),
        ),
    ]
