# Generated by Django 2.2.4 on 2019-08-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190813_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'default_related_name': 'checks', 'verbose_name': 'Check', 'verbose_name_plural': 'Checks'},
        ),
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Checks', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='api.ServicePercentage'),
        ),
    ]
