# Generated by Django 2.2.4 on 2019-08-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190813_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tableid',
            new_name='table',
        ),
    ]
